#!/bin/sh

$HOME/.config/polybar/launch.sh

bspc monitor DVI-D-1 -d ༡ ༢ ༣
bspc monitor DP-1    -d ༤ ༥ ༦
bspc monitor DVI-I-1 -d ༧ ༨ ༩

bspc config border_width        1
bspc config window_gap          10
bspc config top_padding         5
bspc config left_padding        5
bspc config right_padding       5
bspc config bottom_padding      5

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance    	false
bspc config history_aware_focus  	true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config click_to_focus        false
bspc config adaptive raise        true

bspc config center_pseudo_tiled   true

bspc config initial_polarity first_child

bspc config normal_border_color   "#181a26"
bspc config focused_border_color  "#c153f9"
bspc config presel_feedback_color "#181a26"

bspc rule -a mpv state=floating
bspc rule -a firefox:firefox state=floating rectangle=0x0+1100+700
bspc rule -a 'Tor Browser' state=floating
bspc rule -a rofi focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
